name: component-ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  component:
    uses: ovx-labs/ov-ci/.github/workflows/reusable-component-ci.yml@main
    with:
      component: ov-gfx-plugin
      submodules: recursive
      validation-command: python3 ci/validate_repo.py
